---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ATTENDEE_SERVICE_URL: https://attendee-service-blue-chiropodical-accompaniment

inputs:
- name: attendee-service-source

run:
  path: attendee-service-source/ci/tasks/route.sh
