---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/AnithaEdith/pcf-attendee-service-code
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.system.cumuluslabs.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: aedith-PAL-JAN8
    space: qa
    skip_cert_check: true

jobs:
- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest.yml
      path: package-output/attendee-service.jar
